#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-detroit-gem
Version  : 0.4.0
Release  : 3
URL      : https://rubygems.org/downloads/detroit-gem-0.4.0.gem
Source0  : https://rubygems.org/downloads/detroit-gem-0.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : ruby
BuildRequires : rubygem-detroit
BuildRequires : rubygem-detroit-standard
BuildRequires : rubygem-rdoc

%description
# Detroit Gem Tool
[Website](http://rubyworks.github.com/detroit-gem) /
[Report Issue](http://gem.com/rubyworks/detroit-gem/issues) /
[Development](http://gem.com/rubyworks/detroit-gem)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n detroit-gem-0.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-detroit-gem.gemspec

%build
gem build rubygem-detroit-gem.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
detroit-gem-0.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/detroit-gem-0.4.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/assemble%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/autospec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/cdesc-Gem.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/create_gemspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/gemspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/initialize_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/install%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/install-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/load_gemspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/lookup_gemspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/package-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/package_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/pkgdir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/prepackage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/prerequisite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/purge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/Gem/yaml%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/Detroit/cdesc-Detroit.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/page-NOTICE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-gem-0.4.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/NOTICE.txt
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/lib/detroit-gem.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/man/detroit-gem.5
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/man/detroit-gem.5.html
/usr/lib64/ruby/gems/2.2.0/gems/detroit-gem-0.4.0/man/detroit-gem.5.ronn
/usr/lib64/ruby/gems/2.2.0/specifications/detroit-gem-0.4.0.gemspec
